"""add to model User role

Revision ID: 44aae8e48aae
Revises: 
Create Date: 2025-05-11 07:25:02.042855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '44aae8e48aae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### create ENUM type userrole ###
    conn = op.get_bind()
    stmt = "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole')"
    result = conn.execute(sa.text(stmt)).scalar()
    if not result:
        conn.execute(sa.text("CREATE TYPE userrole AS ENUM('USER', 'MODERATOR', 'ADMIN')"))


    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=True))
    op.execute("UPDATE users SET role='USER' WHERE role IS NULL")
    op.alter_column('users', column_name='role', nullable=False)
    op.alter_column('users', 'role', nullable=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=3), nullable=False, comment='First name:'),
    sa.Column('last_name', sa.String(length=3), nullable=False, comment='Last name:'),
    sa.Column('email', sa.String(length=5), nullable=False, comment='Email:'),
    sa.Column('phone', sa.String(length=10), nullable=True, comment='Phone:'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='Birthday:'),
    sa.Column('additional_info', sa.String(length=255), nullable=True, comment='Additional info:'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at:'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated at:'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('users')

    # drop ENUM type userrole
    conn = op.get_bind()
    stmt = "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole')"
    result = conn.execute(sa.text(stmt)).scalar()
    if result:
        conn.execute(sa.text('DROP TYPE userrole'))
    # ### end Alembic commands ###
