"""add to model User email and avatar

Revision ID: 987317ddbfa3
Revises: 44aae8e48aae
Create Date: 2025-05-11 08:41:59.733148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '987317ddbfa3'
down_revision: Union[str, None] = '44aae8e48aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('users')]


    # ### commands auto generated by Alembic - please adjust! ###
    if 'avatar' not in columns:
        op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))

    if 'confirmed' not in columns:
        op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
        op.execute("UPDATE users SET confirmed = TRUE WHERE confirmed IS NULL")
        op.alter_column('users', column_name='confirmed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
