# CONTACT

FIRST_NAME_MIN_LENGTH = 3
FIRST_NAME_MAX_LENGTH = 16
LAST_NAME_MIN_LENGTH = 3
LAST_NAME_MAX_LENGTH = 16
EMAIL_MIN_LENGTH = 5
EMAIL_MAX_LENGTH = 255
PHONE_MIN_LENGTH = 10
PHONE_MAX_LENGTH = 15
ADDITIONAL_INFO_MAX_LENGTH = 255

# USER

USERNAME_MIN_LENGTH = 2
USERNAME_MAX_LENGTH = 16
USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 20